const express = require('express');
const router = express.Router();

const auth = require('../middleware/authMiddleware');
const role = require('../middleware/roleMiddleware');

const {
    getDashboardSummary,
    getBranchPerformance,
    getMonthlySalesReport
} = require('../controllers/directorController');


// All routes here require Director role
router.use(auth);
router.use(role('Director'));


// Director Dashboard Summary
/**
 * @swagger
 * /dashboard/summary:
 *   get:
 *     summary: Get dashboard summary statistics
 *     description: Retrieves key system statistics including total stock across all branches, total revenue from cash sales, and total outstanding credit amounts.
 *     tags:
 *       - Dashboard
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Dashboard summary retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 totalStock:
 *                   type: number
 *                   description: Total quantity of stock available across all branches
 *                   example: 12000
 *                 totalRevenue:
 *                   type: number
 *                   description: Total revenue generated from cash sales
 *                   example: 35000000
 *                 outstandingCredits:
 *                   type: number
 *                   description: Total amount of unpaid credit sales
 *                   example: 8500000
 *       500:
 *         description: Server error
 */
router.get('/dashboard', getDashboardSummary);

// Branch Performance Report



/**
 * @swagger
 * tags:
 *   name: Branches
 *   description: Branch performance operations
 */

/**
 * @swagger
 * /branches/performance:
 *   get:
 *     summary: Get branch performance
 *     description: Retrieve total revenue and total quantity sold per branch from cash sales.
 *     tags: [Branches]
 *     responses:
 *       200:
 *         description: Branch performance data retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   _id:
 *                     type: string
 *                     description: Branch name
 *                     example: "Kampala Branch"
 *                   totalRevenue:
 *                     type: number
 *                     description: Total revenue generated by the branch
 *                     example: 1500000
 *                   totalQuantitySold:
 *                     type: number
 *                     description: Total quantity sold in kilograms
 *                     example: 1200
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "An error occurred while fetching branch performance"
 */

router.get('/branch-performance', getBranchPerformance);

// Monthly Sales Report

/**
 * @swagger
 * tags:
 *   name: Sales
 *   description: Sales reporting and analytics
 */

/**
 * @swagger
 * /sales/monthly-report:
 *   get:
 *     summary: Get monthly sales report
 *     description: Retrieve total revenue per month aggregated from cash sales.
 *     tags: [Sales]
 *     responses:
 *       200:
 *         description: Monthly sales report retrieved successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   _id:
 *                     type: object
 *                     properties:
 *                       year:
 *                         type: integer
 *                         example: 2026
 *                       month:
 *                         type: integer
 *                         description: Month number (1-12)
 *                         example: 3
 *                   totalRevenue:
 *                     type: number
 *                     description: Total revenue generated in that month
 *                     example: 500000
 *       500:
 *         description: Internal server error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "An error occurred while fetching monthly sales report"
 */

router.get('/monthly-sales', getMonthlySalesReport);

module.exports = router;